### ISSUE TITLE
Failed to install in Termux

### ISSUE THREAD

**Issue by imaazkhalid** [es3n1n/re-unplayplay#10]
```
Collecting re-unplayplay (from votify)
  Downloading re_unplayplay-1.2.5.tar.gz (146 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... error
  error: subprocess-exited-with-error

  × pip subprocess to install backend dependencies did not run successfully.
  │ exit code: 1
  ╰─> [95 lines of output]
      Collecting cmake>=3.15
        Downloading cmake-3.30.5.tar.gz (31 kB)
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'
        Installing backend dependencies: started
        Installing backend dependencies: finished with status 'error'
        error: subprocess-exited-with-error

        × pip subprocess to install backend dependencies did not run successfully.
        │ exit code: 2
        ╰─> [72 lines of output]
            Collecting cmake
              Using cached cmake-3.30.5.tar.gz (31 kB)
            ERROR: Exception:
            Traceback (most recent call last):
              File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/pip/_internal/cli/base_command.py", line 105, in _run_wrapper
                status = _inner_run()
                         ^^^^^^^^^^^^
              File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/pip/_internal/cli/base_command.py", line 96, in _inner_run
                return self.run(options, args)
                       ^^^^^^^^^^^^^^^^^^^^^^^
              File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/pip/_internal/cli/req_command.py", line 67, in wrapper
                return func(self, options, args)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^
              File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/pip/_internal/commands/install.py", line 393, in run
                requirement_set = resolver.resolve(
                                  ^^^^^^^^^^^^^^^^^
              File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 95, in resolve
                result = self._result = resolver.resolve(
                                        ^^^^^^^^^^^^^^^^^
              File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/pip/_vendor/resolvelib/resolvers.py", line 546, in resolve
                state = resolution.resolve(requirements, max_rounds=max_rounds)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/pip/_vendor/resolvelib/resolvers.py", line 397, in resolve
                self._add_to_criteria(self.state.criteria, r, parent=None)
              File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/pip/_vendor/resolvelib/resolvers.py", line 173, in _add_to_criteria
                if not criterion.candidates:
                       ^^^^^^^^^^^^^^^^^^^^
              File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/pip/_vendor/resolvelib/structs.py", line 156, in __bool__
                return bool(self._sequence)
                       ^^^^^^^^^^^^^^^^^^^^
              File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 174, in __bool__
                return any(self)
                       ^^^^^^^^^
              File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 162, in <genexpr>
                return (c for c in iterator if id(c) not in self._incompatible_ids)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 53, in _iter_built
                candidate = func()
                            ^^^^^^
              File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 186, in _make_candidate_from_link
                base: Optional[BaseCandidate] = self._make_base_candidate_from_link(
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 232, in _make_base_candidate_from_link
                self._link_candidate_cache[link] = LinkCandidate(
                                                   ^^^^^^^^^^^^^^
              File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 303, in __init__
                super().__init__(
              File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 158, in __init__
                self.dist = self._prepare()
                            ^^^^^^^^^^^^^^^
              File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 235, in _prepare
                dist = self._prepare_distribution()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 314, in _prepare_distribution
                return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/pip/_internal/operations/prepare.py", line 527, in prepare_linked_requirement
                return self._prepare_linked_requirement(req, parallel_builds)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/pip/_internal/operations/prepare.py", line 642, in _prepare_linked_requirement
                dist = _get_prepared_distribution(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/pip/_internal/operations/prepare.py", line 71, in _get_prepared_distribution
                with build_tracker.track(req, tracker_id):
              File "/data/data/com.termux/files/usr/lib/python3.12/contextlib.py", line 137, in __enter__
                return next(self.gen)
                       ^^^^^^^^^^^^^^
              File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/pip/_internal/operations/build/build_tracker.py", line 136, in track
                self.add(req, tracker_id)
              File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/pip/_internal/operations/build/build_tracker.py", line 102, in add
                raise LookupError(message)
            LookupError: https://files.pythonhosted.org/packages/5b/b9/25938832b55a1ee59f11c55068107edeab9abdb2db873721c9aa405108f3/cmake-3.30.5.tar.gz (from https://pypi.org/simple/cmake/) (requires-python:>=3.7) is already being built: cmake>=3.15 from https://files.pythonhosted.org/packages/5b/b9/25938832b55a1ee59f11c55068107edeab9abdb2db873721c9aa405108f3/cmake-3.30.5.tar.gz
            [end of output]

        note: This error originates from a subprocess, and is likely not a problem with pip.
      error: subprocess-exited-with-error

      × pip subprocess to install backend dependencies did not run successfully.
      │ exit code: 2
      ╰─> See above for output.

      note: This error originates from a subprocess, and is likely not a problem with pip.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install backend dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by imaazkhalid** [comment]
Getting same thing on cmake as well

**Comment by imaazkhalid** [comment]
Installed cmake using pkg/apt and got different errors this time


```
~ $ pip install votify
Collecting votify
  Using cached votify-1.4.2-py3-none-any.whl.metadata (13 kB)
Collecting click (from votify)
  Using cached click-8.1.7-py3-none-any.whl.metadata (3.0 kB)
Collecting inquirerpy (from votify)
  Using cached InquirerPy-0.3.4-py3-none-any.whl.metadata (8.1 kB)
Collecting pillow (from votify)
  Downloading pillow-11.0.0.tar.gz (46.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.7/46.7 MB 85.9 kB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting protobuf (from votify)
  Downloading protobuf-5.28.2-py3-none-any.whl.metadata (592 bytes)
Collecting pybase62 (from votify)
  Downloading pybase62-1.0.0-py3-none-any.whl.metadata (3.7 kB)
Collecting pycryptodome (from votify)
  Downloading pycryptodome-3.21.0.tar.gz (4.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.8/4.8 MB 33.5 kB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting pywidevine (from votify)
  Downloading pywidevine-1.8.0-py3-none-any.whl.metadata (9.1 kB)
Collecting re-unplayplay (from votify)
  Downloading re_unplayplay-1.2.5.tar.gz (146 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: yt-dlp in /data/data/com.termux/files/usr/lib/python3.12/site-packages (from votify) (2024.10.7)
Collecting pfzy<0.4.0,>=0.3.1 (from inquirerpy->votify)
  Downloading pfzy-0.3.4-py3-none-any.whl.metadata (4.9 kB)
Collecting prompt-toolkit<4.0.0,>=3.0.1 (from inquirerpy->votify)
  Downloading prompt_toolkit-3.0.48-py3-none-any.whl.metadata (6.4 kB)
Collecting PyYAML<7.0.0,>=6.0.1 (from pywidevine->votify)
  Downloading pyyaml-6.0.2.tar.gz (130 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting Unidecode<2.0.0,>=1.3.7 (from pywidevine->votify)
  Downloading Unidecode-1.3.8-py3-none-any.whl.metadata (13 kB)
Collecting protobuf (from votify)
  Downloading protobuf-4.25.5-py3-none-any.whl.metadata (541 bytes)
Collecting pymp4<2.0.0,>=1.4.0 (from pywidevine->votify)
  Downloading pymp4-1.4.0-py3-none-any.whl.metadata (2.9 kB)
Requirement already satisfied: requests<3.0.0,>=2.31.0 in /data/data/com.termux/files/usr/lib/python3.12/site-packages (from pywidevine->votify) (2.32.3)
Requirement already satisfied: brotli in /data/data/com.termux/files/usr/lib/python3.12/site-packages (from yt-dlp->votify) (1.1.0)
Requirement already satisfied: certifi in /data/data/com.termux/files/usr/lib/python3.12/site-packages (from yt-dlp->votify) (2024.8.30)
Requirement already satisfied: mutagen in /data/data/com.termux/files/usr/lib/python3.12/site-packages (from yt-dlp->votify) (1.47.0)
Requirement already satisfied: pycryptodomex in /data/data/com.termux/files/usr/lib/python3.12/site-packages (from yt-dlp->votify) (3.21.0)
Requirement already satisfied: urllib3<3,>=1.26.17 in /data/data/com.termux/files/usr/lib/python3.12/site-packages (from yt-dlp->votify) (2.2.3)
Requirement already satisfied: websockets>=13.0 in /data/data/com.termux/files/usr/lib/python3.12/site-packages (from yt-dlp->votify) (13.1)
Collecting wcwidth (from prompt-toolkit<4.0.0,>=3.0.1->inquirerpy->votify)
  Downloading wcwidth-0.2.13-py2.py3-none-any.whl.metadata (14 kB)
Collecting construct==2.8.8 (from pymp4<2.0.0,>=1.4.0->pywidevine->votify)
  Downloading construct-2.8.8.tar.gz (717 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 717.7/717.7 kB 31.3 kB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: charset-normalizer<4,>=2 in /data/data/com.termux/files/usr/lib/python3.12/site-packages (from requests<3.0.0,>=2.31.0->pywidevine->votify) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /data/data/com.termux/files/usr/lib/python3.12/site-packages (from requests<3.0.0,>=2.31.0->pywidevine->votify) (3.10)
Downloading votify-1.4.2-py3-none-any.whl (33 kB)
Downloading click-8.1.7-py3-none-any.whl (97 kB)
Downloading InquirerPy-0.3.4-py3-none-any.whl (67 kB)
Downloading pybase62-1.0.0-py3-none-any.whl (4.9 kB)
Downloading pywidevine-1.8.0-py3-none-any.whl (70 kB)
Downloading protobuf-4.25.5-py3-none-any.whl (156 kB)
Downloading pfzy-0.3.4-py3-none-any.whl (8.5 kB)
Downloading prompt_toolkit-3.0.48-py3-none-any.whl (386 kB)
Downloading pymp4-1.4.0-py3-none-any.whl (14 kB)
Downloading Unidecode-1.3.8-py3-none-any.whl (235 kB)
Downloading wcwidth-0.2.13-py2.py3-none-any.whl (34 kB)
Building wheels for collected packages: pillow, pycryptodome, re-unplayplay, construct, PyYAML
  Building wheel for pillow (pyproject.toml) ... done
  Created wheel for pillow: filename=pillow-11.0.0-cp312-cp312-linux_armv7l.whl size=1068783 sha256=0a9daccf523150a666d04be07a3763f44b1fd767356bb7643ba8dd130cd60cdb
  Stored in directory: /data/data/com.termux/files/home/.cache/pip/wheels/9f/5b/7b/4f5c7bb46d78f484a91952ff368a2d77f86ec9daad6f6a8785
  Building wheel for pycryptodome (pyproject.toml) ... done
  Created wheel for pycryptodome: filename=pycryptodome-3.21.0-cp36-abi3-linux_armv7l.whl size=2024408 sha256=7a9b49f0cf8b869456ca5ecf40380180c6f66dce0366d6f77697c7607d12f1ad
  Stored in directory: /data/data/com.termux/files/home/.cache/pip/wheels/ea/b0/66/b4e0c7bf7c2e546194481eb0705943f686798e50793b2be61e
  Building wheel for re-unplayplay (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for re-unplayplay (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [33 lines of output]
      *** scikit-build-core 0.10.7 using CMake 3.30.5 (wheel)
      *** Configuring CMake...
      loading initial cache file /data/data/com.termux/files/usr/tmp/tmp8bj9z4xo/build/CMakeInit.txt
      -- [cmkr] Skipping automatic cmkr generation
      -- The CXX compiler identification is Clang 19.1.2
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /data/data/com.termux/files/usr/bin/arm-linux-androideabi-clang++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Fetching pybind11 (v2.13.6)...
      CMake Error at /data/data/com.termux/files/usr/share/cmake-3.30/Modules/ExternalProject/shared_internal_commands.cmake:951 (message):
        error: could not find git for clone of pybind11-populate
      Call Stack (most recent call first):
        /data/data/com.termux/files/usr/share/cmake-3.30/Modules/ExternalProject.cmake:3035 (_ep_add_download_command)
        CMakeLists.txt:29 (ExternalProject_Add)


      -- Configuring incomplete, errors occurred!

      CMake Error at /data/data/com.termux/files/usr/share/cmake-3.30/Modules/FetchContent.cmake:1906 (message):
        CMake step for pybind11 failed: 1
      Call Stack (most recent call first):
        /data/data/com.termux/files/usr/share/cmake-3.30/Modules/FetchContent.cmake:1609 (__FetchContent_populateSubbuild)
        /data/data/com.termux/files/usr/share/cmake-3.30/Modules/FetchContent.cmake:2145:EVAL:2 (__FetchContent_doPopulation)
        /data/data/com.termux/files/usr/share/cmake-3.30/Modules/FetchContent.cmake:2145 (cmake_language)
        /data/data/com.termux/files/usr/share/cmake-3.30/Modules/FetchContent.cmake:2384 (__FetchContent_Populate)
        CMakeLists.txt:68 (FetchContent_MakeAvailable)


      -- Configuring incomplete, errors occurred!

      *** CMake configuration failed
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for re-unplayplay
  Building wheel for construct (pyproject.toml) ... done
  Created wheel for construct: filename=construct-2.8.8-py2.py3-none-any.whl size=69822 sha256=b4c48ba7faffc3fffbfb41c0a99af6aa0e5d9f3a95d4eb7ed6090e639eed9140
  Stored in directory: /data/data/com.termux/files/home/.cache/pip/wheels/a2/8e/56/88484f05befc105a8b86e3b0a2799d18a71e80ef5525c3f1b7
  Building wheel for PyYAML (pyproject.toml) ... done
  Created wheel for PyYAML: filename=PyYAML-6.0.2-cp312-cp312-linux_armv7l.whl size=45360 sha256=c6cf5eb6be9fa70e5877142fea4c64c7a409908b55e15f5afa18707e64d6e17c
  Stored in directory: /data/data/com.termux/files/home/.cache/pip/wheels/db/db/e2/4a1264f6c5192c518338cd8c226caae9f43c610fdb76c1ebcb
Successfully built pillow pycryptodome construct PyYAML
Failed to build re-unplayplay
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (re-unplayplay)
~ $

**Comment by SuisChan** [comment]
> error: could not find git for clone of pybind11-populate

huh?

**Comment by es3n1n** [comment]
@imaazkhalid do you have git installed? If not, please install git

**Comment by imaazkhalid** [comment]
@es3n1n thanks a lot! This fixed it.
It installed successfully.
